### PR TITLE
Adapt vllm custom ar into sgl-kernel

### PR DESCRIPTION
**Pull request by yizhang2077**
## Motivation

Adapt vllm custom ar into sgl-kernel as a following step for #2244 
## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
cooooool

**Comment by zhyncs** [comment]
I walked through at this PR, and there are a few main points:
1. Before this, we need to support docker build and pypi wheels updates. ref https://github.com/sgl-project/sglang/pull/2306
2. Add unit tests.
3. After publishing the custom all reduce part to sgl-kernel, replace the implementation in main.
4. If tensorrt llm custom all reduce performs better, do we still need the vllm part?

**Comment by zhyncs** [comment]
BTW I can also accept dividing it into N parts and integrating them at the end, which will make it easier to review when broken down into smaller sections.

**Comment by zhyncs** [comment]
> I walked through at this PR, and there are a few main points:
> 
> 1. Before this, we need to support docker build and pypi wheels updates. ref [misc: update build setup #2306](https://github.com/sgl-project/sglang/pull/2306)
> 2. Add unit tests.
> 3. After publishing the custom all reduce part to sgl-kernel, replace the implementation in main.
> 4. If tensorrt llm custom all reduce performs better, do we still need the vllm part?

If the conclusion can be drawn from local verification in point 4, we should be able to make a choice. Point 1 seems to need to be done first. Points 2 and 3 can be placed in follow-up PRs.

**Comment by yizhang2077** [comment]
Since we decide use trt llm as custom allreduce kernel, we stop this pr

**Pull request closed without merging**
