### PR TITLE
add awq marlin

### PR DESCRIPTION
**Pull request by haichuan1221**
As the name suggests, add awq marlin from vllm

### CODE REVIEW

**Review by zhyncs — COMMENTED** [review]
May you benchmark the performance of BF16, AWQ, AWQ Marlin for Llama 3.1 8B Instruct? Thanks.

**Comment by zhyncs** [comment]
Maybe `python3 -m sglang.bench_serving --backend sglang` is ok.

**Comment by haichuan1221** [comment]
> May you benchmark the performance of BF16, AWQ, AWQ Marlin for Llama 3.1 8B Instruct? Thanks.

Yes, I will do so

**Comment by Ying1123** [comment]
It seems you are updating some code that will not be used. What is wrong if you just load awq-marlin checkpoints?
#826 should be enough.

BTW, once you get performance numbers, please share them here.

**Comment by haichuan1221** [comment]
> ce you get performance numbers, please share t

Yes, you are right. Vllm use awq_marlin if awq can converted to marlin as shown: https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/quantization/awq_marlin.py#L71.

**Pull request closed without merging**
