### PR TITLE
add filter_files_not_needed_for_inference

### PR DESCRIPTION
**Pull request by haichuan1221**
It seems there are some missing format for the model loader, such as filter_files_not_needed_for_inference,np_cache_weights_iterator, pt_weights_iterator etc. Do you guys want to support it or remove it?

### CODE REVIEW

**Comment by zhyncs** [comment]
Hi @haichuan1221 Thanks for your contribution. May you add a unit test for it? Thanks.

**Comment by haichuan1221** [comment]
> Hi @haichuan1221 Thanks for your contribution. May you add a unit test for it? Thanks.

Will do this later

**Comment by Ying1123** [comment]
The code you are modifying is for an experimental feature that will likely never be used. How do you reach this code? What is your server launch command?

**Comment by haichuan1221** [comment]
> The code you are modifying is for an experimental feature that will likely never be used. How do you reach this code? What is your server launch command?

Well, it has never been used, so I suggest just removing it. Also, it will download files from huggingface even if they already exist and I fixed it. Can you please review the code again?

**Pull request closed without merging**
