### PR TITLE
Optimize radix tree matching

### PR DESCRIPTION
**Pull request by ispobock**
Use the first token to find child, avoiding traversing all children.

### CODE REVIEW

**Comment by merrymercy** [comment]
@ispobock This seems to be an interesting optimization.
Did you check the correctness of many workloads? Did you notice any performance improvements?

**Comment by ispobock** [comment]
@merrymercy I tested on mmlu dataset with different parallel, the accuracy is the same with the main branch. The total latency has slight improvement.

| with optimization | parallel | total latency | avg accuracy  |
|-------------------|----------|---------------|---------------|
| N                 | 64       | 258.204       | 0.528         |
| Y                 | 64       | 257.729       | 0.528         |
| N                 | 128      | 254.929       | 0.528         |
| Y                 | 128      | 254.867       | 0.528         |

I also test on sharegpt dataset with 1000 prompts and found the throughput has slight improvement.
without optimization:
```
Total time: 175.29 s
Throughput: 5.70 requests/s
Average latency: 65.24 s
Average latency per token: 0.18 s
Average latency per output token: 1.10 s
```
with optimization:
```
Total time: 173.21 s
Throughput: 5.77 requests/s
Average latency: 64.15 s
Average latency per token: 0.17 s
Average latency per output token: 1.08 s
```

Test env:
- model: llama2_13b_chat
- gpu: 1 A100 80G

Reproduce:
```
python -m sglang.launch_server --model-path /workdir/llama2_13b_chat/ --port 30000

python benchmark/mmlu/bench_sglang.py

python benchmark/latency_throughput/bench_throughput.py --backend srt --tokenizer /workdir/llama2_13b_chat/ --dataset /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 1000 --request-rate 128 --port 30000
```

**Comment by ispobock** [comment]
For 5000 prompts of sharegpt dataset benchmark, the throughput is improved **11.2%** with this optimization.
without optimization:
```
Total time: 973.67 s
Throughput: 5.14 requests/s
Average latency: 439.68 s
Average latency per token: 1.17 s
Average latency per output token: 10.23 s
```
with optimization:
```
Total time: 874.84 s
Throughput: 5.72 requests/s
Average latency: 382.35 s
Average latency per token: 1.01 s
Average latency per output token: 8.91 s
```

**Comment by merrymercy** [comment]
Awesome! cc @hnyls2002 @Ying1123

**Pull request merged**
