### PR TITLE
Support Mistral-Nemo

### PR DESCRIPTION
**Pull request by ispobock**
Tested Mistral-Nemo-Instruct-2407

hf:
```
prefill logits tensor([-10.2812, -10.2812,   1.8486,  ..., -11.5391,  -9.4219,  -7.6758], device='cuda:0')
prefill logits tensor([-11.0547, -11.0547,   2.1035,  ..., -11.6797,  -9.8516,  -9.5234], device='cuda:0')
prefill logits tensor([-8.1562, -8.1562,  1.1504,  ..., -9.5078, -6.8477, -9.3906], device='cuda:0')
```

sglang:
```
tensor([[-10.3125, -10.3125,   1.7656,  ..., -11.6250,  -9.4375,  -7.7500],
        [-11.1250, -11.1250,   2.0469,  ..., -11.6875,  -9.9375,  -9.5625],
        [ -8.1250,  -8.1250,   1.0938,  ...,  -9.5000,  -6.8438,  -9.4375]],
       device='cuda:0', dtype=torch.bfloat16)
```

### CODE REVIEW

**Review by zhyncs — APPROVED** [review]
LGTM. nit: Maybe run it on the original llama as well.

**Comment by zhyncs** [comment]
ref https://github.com/vllm-project/vllm/pull/6548/files

**Comment by ispobock** [comment]
For Llama-2-13b-chat-hf:

hf:
```
prefill logits tensor([-6.5742, -6.1523,  5.3672,  ..., -2.6953, -1.6221, -2.8848], device='cuda:0')
prefill logits tensor([-6.7305, -6.1836,  5.7305,  ..., -1.7578, -2.8750, -2.7480], device='cuda:0')
prefill logits tensor([-6.0430, -5.4570,  4.8164,  ..., -1.2539, -0.9282, -1.3018], device='cuda:0')
```
sglang:
```
tensor([[-6.5742, -6.1484,  5.3633,  ..., -2.6973, -1.6250, -2.8848],
        [-6.7266, -6.1875,  5.7266,  ..., -1.7539, -2.8770, -2.7441],
        [-6.0391, -5.4570,  4.8125,  ..., -1.2539, -0.9272, -1.3008]],
       device='cuda:0', dtype=torch.float16)
```

**Comment by zhyncs** [comment]
Thanks for your contribution!

**Pull request merged**
