### PR TITLE
Update vocab embedding deps and add TP switch

### PR DESCRIPTION
**Pull request by ispobock**
## Motivation
In some cases, we may use replicated embedding instead of parallel embedding to reduce communication overhead.

### CODE REVIEW

**Comment by zhyncs** [comment]
Cool!

**Comment by zhyncs** [comment]
@ispobock May you change your branch to the https://github.com/sgl-project/sglang repo? I want to run the nightly eval for this.

**Comment by ispobock** [comment]
> @ispobock May you change your branch to the https://github.com/sgl-project/sglang repo? I want to run the nightly eval for this.

Sure. I will create a new branch to run nightly eval.

**Comment by ispobock** [comment]
https://github.com/sgl-project/sglang/actions/runs/11622100414
Nightly eval passed

**Review by merrymercy — APPROVED** [review]

**Pull request merged**
