### PR TITLE
[Feature] Support new parameter - EBNF in xgrammar

### PR DESCRIPTION
**Pull request by adarshxs**
## Motivation
XGrammar enables efficient structured generation. XGrammar backend already support enforcement of EBNF (Extended Backus-Naur Form) grammars.
adds feature requested in: https://github.com/sgl-project/sglang/issues/2376

## Modifications
- added a new parameter called `ebnf` in sampling_params.py and treat it similar to regex and JSON.
- Implemented the `test_ebnf_generate` method to validate multiple valid output patterns based on a complex EBNF grammar.

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [x] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by adarshxs** [comment]
Feature requested by @merrymercy in https://github.com/sgl-project/sglang/issues/2376

TODO: update sampling parameter docs

**Comment by adarshxs** [comment]
fixing some stuff. will reopen soon

**Comment by merrymercy** [comment]
@adarshxs This is a very important feature. Do you have any updates?

**Comment by adarshxs** [comment]
@merrymercy I am still working on a fix for this: The EBNF grammar is not being enforced correctly and some tests are failing.

**Pull request closed without merging**
