### PR TITLE
hotfix: workaround for rmsnorm input dim restriction

### PR DESCRIPTION
**Pull request by zhyncs**
https://github.com/flashinfer-ai/flashinfer/blob/c93f647a0dd6b58c9ac20b39438316202358463c/python/csrc/norm.cu#L28

Thank you for your contribution, we really appreciate it. The following instructions will help improve your pull request and make it easier to receive feedback. If there are any items you don't understand, don't worry. Just submit the pull request and ask the maintainers for help.

## Motivation

Please explain the motivation behind this PR and the goal you aim to achieve with it.

## Modification

Briefly describe the changes made in this PR.

## Checklist

1. Ensure pre-commit `pre-commit run --all-files` or other linting tools are used to fix potential lint issues.
2. Confirm that modifications are covered by complete unit tests. If not, please add more unit tests for correctness.
3. Modify documentation as needed, such as docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
This issue has only been found on DeepSeek V2 MLA TP 8 so far.

**Comment by zhyncs** [comment]
ref 
vllm https://github.com/vllm-project/vllm/blob/6aa33cb2ddd769e764a3312627cab5bffaa383cc/csrc/layernorm_kernels.cu#L295-L296
flashinfer https://github.com/flashinfer-ai/flashinfer/blob/c93f647a0dd6b58c9ac20b39438316202358463c/python/csrc/norm.cu#L28

**Comment by ispobock** [comment]
Fixed in https://github.com/sgl-project/sglang/pull/1066

**Comment by zhyncs** [comment]
> Fixed in #1066

Thanks!

**Pull request closed without merging**
