### PR TITLE
[router] rust-based router

### PR DESCRIPTION
**Pull request by ByronHsu**
## Motivation
https://github.com/sgl-project/sglang/issues/1732

This pull request follows up on https://github.com/sgl-project/sglang/pull/1695 and introduces a new router implementation in Rust that achieves a 2x speedup compared to the old Python router. It achieves comparable performance to our current Data Parallel (`--dp`) implementation (can be further enhanced by moving the intermediate connection to grpc). Moreover, the rust router can support multi-node DP which can not be achieved in the current DP implementation.

## Benchmark

**Benchmark Script:**
```bash
$ python -m sglang.bench_serving --backend sglang --host 127.0.0.1 --port 8080
```

**Detailed Benchmark Results:**
Access the complete benchmark data [here](https://docs.google.com/spreadsheets/d/1Y_dY4EGpk26MsehoWf6K85p7BXBBWlXI-gk6-Ei5-cs/edit?usp=sharing).

**Latency Results:**

| Streaming Latency (ms) | Non-Streaming Latency (ms) |
|------------------------|----------------------------|
| Streaming Latency | Non-Streaming Latency |

--- 

## Modifications

1. Implemented rust http server using `actix web`
2. Implemented router base class, random, and round robin router.
3. Implemented rust python binding which makes python be able to call rust router.

## Usage

Check [readme](https://github.com/sgl-project/sglang/blob/78d35abc8990b4067af2f0a650e4062f41425594/rust/readme.md). The executable is not published via CI yet, will follow up in later PRs.

## TODO

1. Create a standalone pip package (maybe `sglang-router`), consisting of rust generated wheel and python binding.
2. Implement cache aware router
3. Implement fault tolerance logics

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
> Create a standalone pip package (maybe sglang-router), consisting of rust generated wheel and python binding.

It's a good idea. If needed, I can create the repo for you. Details need to be discussed with @merrymercy @Ying1123 
I want to continue making the SGLang project itself more lightweight. Implementing other languages, such as CUDA, C++, and Rust, in separate repositories and providing Python interfaces as whl packages is a good approach.

**Comment by merrymercy** [comment]
@Ying1123 Let us merge this soon?

**Comment by HaiShaw** [comment]
> > Create a standalone pip package (maybe sglang-router), consisting of rust generated wheel and python binding.
> 
> It's a good idea. If needed, I can create the repo for you. Details need to be discussed with @merrymercy @Ying1123 I want to continue making the SGLang project itself more lightweight. Implementing other languages, such as CUDA, C++, and Rust, in separate repositories and providing Python interfaces as whl packages is a good approach.

Having SGLang light weight is good to consider, have a question though, we still need an easy way to associate SGLang with spun off repos (can be multiple or potentially more), e.g. rust-router, C++ kernels, etc. if we go down that route.

**Comment by HaiShaw** [comment]
@ByronHsu Would you please clarify this interesting comment below, what part of rust enables multi-node? Thanks!
`Moreover, the rust router can support multi-node DP which can not be achieved in the current DP implementation.`

**Comment by zhyncs** [comment]
@HaiShaw Regarding this PR, we can consider merging it, as it only involves Python for the model forward part, while the server part can consider other implementations. Additionally, regarding the kernel, I still firmly believe that FlashInfer is the future, and we will continue to stick with this technical approach. For any future kernel-related work, we'll consider using FlashInfer or implementing it within FlashInfer.​​​​​​​​​​​​​​​​

**Comment by HaiShaw** [comment]
@zhyncs Good to know your opinion, I was just thinking what if I want to try out CUTLASS/CK MoE kernels, adding to FlashInfer is possible, discussion to make.

**Comment by austin362667** [comment]
Thank you, @ByronHsu, for the great work, and thanks to @zhyncs and @merrymercy for the review.

> @ByronHsu, could you clarify your interesting comment below? Which part of Rust enables multi-node support? Thanks! Additionally, the Rust router can support multi-node DP, which the current DP implementation does not achieve.

Thanks, @HaiShaw, for the discussion. I believe what @ByronHsu is referring to is that, with the router, SGLang can actually achieve DP in a distributed setting, either with the [Python-based Router](https://github.com/sgl-project/sglang/pull/1695) or the [Rust-based Router](https://github.com/sgl-project/sglang/pull/1790). The [Python-based Router](https://github.com/sgl-project/sglang/pull/1695) was closed due to the low performance. For reference, you can check out the [SGLang paper](https://arxiv.org/pdf/2312.07104), particularly Section A.4, for more details.

**Review by Ying1123 — APPROVED** [review]
Great work! I think it is good to ship this first version after discussion with @merrymercy. And we can refine the http server and maybe also add a grpc server later.

**Comment by ByronHsu** [comment]
@HaiShaw @austin362667 The current DP impl is preliminary and only supports one node. To be specific, it launches one http server only so it cannot handle multiple nodes, where it needs multiple servers and a router server.

@Ying1123 thanks for the kind word. I believe we can refine the rust code better and better as we gradually get more familiar with rust.

**Comment by binarycrayon** [comment]
Is switching to grpc between frontend and backend is part of this effort?

**Pull request merged**
