### PR TITLE
[Fused moe] add tuning fused configs for qwen2 57b and mixtral 8x7b

### PR DESCRIPTION
**Pull request by BBuf**
Using FP8 quantization for inference on RTX 4090 can significantly improve the performance of both Qwen2-57B and Mixtral 8x7B models.

### CODE REVIEW

**Review by zhyncs — COMMENTED** [review]
The FP8 monkey patch hasn't succeeded yet. How does this config work for FP8

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/blob/8912b7637f5c8dca0f18c31a17e46f427cf53152/python/sglang/srt/layers/quantization/__init__.py#L64

**Comment by zhyncs** [comment]
cc @ispobock

**Comment by BBuf** [comment]
> The FP8 monkey patch hasn't succeeded yet. How does this config work for FP8

I have not test fp8 fused moe in sglang yet, but tested in vllm:

benchmark:

```shell
python3 -m vllm.entrypoints.openai.api_server --model /mnt/bbuf/Qwen2-57B-A14B-Instruct-FP8 -tp 4 --trust-remote-code --max-model-len 4096 --gpu-memory-utilization 0.9 --disable-log-requests --swap-space 16 --kv-cache-dtype fp8 --distributed-executor-backend ray 


python3 benchmarks/benchmark_serving.py --model /mnt/bbuf/Qwen2-57B-A14B-Instruct-FP8 --num-prompts 500 --host 127.0.0.1  --save-result --result-dir result --sharegpt-output-len 256 --request-rate 32 --dataset-name sharegpt --dataset-path /mnt/bbuf/upstream-vllm/hongan-data/ShareGPT_V3_unfiltered_cleaned_split.json
```

Without tuning:

图片

With Tuning:

图片

图片

We can use this optimized  config in GTX 4090 once sglang fp8 fused_moe ready.

**Review by zhyncs — APPROVED** [review]

**Pull request merged**
