### PR TITLE
[Minor] Improve logging and rename the health check endpoint name

### PR DESCRIPTION
**Pull request by merrymercy**
- Log the whole request instead of input text only
- Rename `/v1/health` to `/health_generate` for the health check in #1154. The endpoint name "/v1" are for openai APIs so we do not want to use it for SRT endpoints.
- Other minor style improvement

### CODE REVIEW

**Comment by Xu-Chen** [comment]
We found that when cuda-graph is turned on, the service will hunag after more than 200 consecutive` /health_generate` requests (1 req/s ). ` set --disable-cuda-graph ` can help solve this problem.  Can be reproduced in 0.3.0 with 4* A100.

**Comment by zhyncs** [comment]
May u try the latest main? Thanks!

**Comment by Xu-Chen** [comment]
> May u try the latest main? Thanks!

 Can be reproduced in the latest main with 4* A100.

curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
done 378

Test code
```bash
#!/bin/bash
i=0
while true
do
	curl -m 60 "http://127.0.0.1:8080/health_generate"
	i=$((i+1))
	echo "done $i"
done
```


error log
```python
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/models/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 448, in _wait_for_response
    await asyncio.wait_for(state.event.wait(), timeout=4)
  File "/opt/conda/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/models/sglang/python/sglang/srt/server.py", line 119, in health_generate
    async for _ in tokenizer_manager.generate_request(gri, request):
  File "/data/models/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 157, in generate_request
    async for response in self._handle_single_request(obj, request):
  File "/data/models/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 284, in _handle_single_request
    async for response in self._wait_for_response(state, obj, rid, request):
  File "/data/models/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 453, in _wait_for_response
    raise ValueError(f"Abort request {rid}")
ValueError: Abort request e077560737d94a788c6a8670c98bf3e8
```

**Comment by Xu-Chen** [comment]
> May u try the latest main? Thanks!


Any ideas on this issue?

**Pull request merged**
