### PR TITLE
fix test_embedding_models prompt length too long's bug

### PR DESCRIPTION
**Pull request by BBuf**
linked pr: https://github.com/sgl-project/sglang/pull/2014#issuecomment-2470115834

@zhyncs

### CODE REVIEW

**Comment by BBuf** [comment]
If I truncate prompt length to `max_model_length-1`, I can pass the unittest. But ci's performace test failed, is it necessary to reconstruct some prompts for testing the embedding model to avoid errors caused by exceeding the model's maximum length and to prevent CI performance tests from failing due to truncation?" @zhyncs

**Comment by BBuf** [comment]
> If I truncate prompt length to `max_model_length-1`, I can pass the unittest. But ci's performace test failed, is it necessary to reconstruct some prompts for testing the embedding model to avoid errors caused by exceeding the model's maximum length and to prevent CI performance tests from failing due to truncation?" @zhyncs

Or can we relax performace test's throught for embedding model's test ?

**Comment by merrymercy** [comment]
This looks good.

1. The failed performance test is unrelated. It is due to the unstable CI machines.
2. Can you fix the lint errors? You can use pre-commit https://sgl-project.github.io/references/contributor_guide.html#format-your-code

**Comment by BBuf** [comment]
> This looks good.
> 
>     1. The failed performance test is unrelated. It is due to the unstable CI machines.
> 
>     2. Can you fix the lint errors? You can use pre-commit https://sgl-project.github.io/references/contributor_guide.html#format-your-code

Ok, I will fix it later.

**Pull request merged**
