### PR TITLE
Support qwen2 vl model 

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

done by @yizhang2077 @ispobock 

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/actions/runs/11423313809

**Comment by zhyncs** [comment]
BTW @yizhang2077 have u joined our slack channel https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2ngly9muu-t37XiH87qvD~6rVBTkTEHw

**Comment by zhyncs** [comment]
Nightly eval passed. The issue with ut will be resolved in the follow-up. cc @yizhang2077

**Comment by merrymercy** [comment]
@zhyncs @yizhang2077  @ispobock Great work!

**Comment by zhyncs** [comment]
The code development work was completed by @yizhang2077 and @ispobock, I just helped confirm the nightly eval. Welcome @yizhang2077 as a new committer to SGLang, looking forward to long-term contributions in the future!

**Pull request merged**
