### PR TITLE
Time cost utils

### PR DESCRIPTION
**Pull request by hnyls2002**
This PR introduces `--show-cost-time` server argument and change the cost time mark style.

### CODE REVIEW

**Comment by csbo98** [comment]
@hnyls2002  Hi, thank you for your outstanding contribution for this pr. I'm quite interested in the feature proposed in this PR, but I still have some questions. As of now, it hasn't been actively used in sglang. What is the purpose of --show-cost-time, and in what scenarios would it be enabled? Since both mark_start and mark_end involve CUDA synchronization, I assume this feature wouldn't be suitable for production use?

**Comment by hnyls2002** [comment]
@csbo98 It is only for debugging and profiling. For now, we'd better suggest using torch profile or nsys. It is true that if you want to profile every part of SGLang precisely, the extra synchronization overhead cannot be avoided.

In the production, we have `/metrics` API, which is not for directly calculating the running time for each part of the code, but it can reflect our performance through metrics such as throughput.

**Comment by hnyls2002** [comment]
@csbo98 There is another way to get the real-time consumption for each part of the code. There are some natural synchronizations in SGLang, like all the `to_list` or `cpu` operations. You can add a time counter here to get the profiling without loss.

**Comment by csbo98** [comment]
@hnyls2002 Thank you very much for your detailed reply.

**Pull request merged**
