### PR TITLE
[Performance, Hardware] MoE tuning on AMD MI300x GPUs

### PR DESCRIPTION
**Pull request by kkHuang-amd**
## Motivation
Optimize MoE kernel performance for AMD platform

## Modifications
Add configuration file

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Review by HaiShaw — APPROVED** [review]
@kkHuang-amd LGTM. Thanks for the great work!

**Comment by HaiShaw** [comment]
@merrymercy @Ying1123 Would you please have a review?

**Comment by merrymercy** [comment]
@kkHuang-amd Thanks for the contribution. Can you also take a look at attention kernels https://github.com/sgl-project/sglang/tree/main/python/sglang/srt/layers/attention/triton_ops?

**Comment by HaiShaw** [comment]
@merrymercy my preliminary parameters search for `attention/triton_ops` did not lead to much better results from current settings. I hope @kkHuang-amd find it different.

**Pull request merged**
