### PR TITLE
[WIP] [Formater] Replace black with ruff

### PR DESCRIPTION
**Pull request by Qubitium**
Reason for PR:

1. ruff is faster
2. ruff is PEP compliant
3. ruff is much saner than black: black sometimes like to create new lines or bloat code into multiple lines for no logical reason
4. ruff is compatible with black rules

The PR diff shows the improvements while staying both PEP compliant and retain/improve legibility. 

```
# ruff version 0.3.4
pip install ruff==0.3.4
```

### CODE REVIEW

**Comment by hnyls2002** [comment]
@Qubitium Why `ruff --fix` format code like this ?

https://github.com/sgl-project/sglang/pull/335/files#diff-192192a73b4db4b25f305dc49a35aeb3e86789d78b07c01b589243e2f2da9b18R8-R9

I tested but it does not compress the lines.

**Comment by Qubitium** [comment]
> @Qubitium Why `ruff --fix` format code like this ?
> 
> https://github.com/sgl-project/sglang/pull/335/files#diff-192192a73b4db4b25f305dc49a35aeb3e86789d78b07c01b589243e2f2da9b18R8-R9
> 
> I tested but it does not compress the lines.


1. ruff removed all the imports that were never used in the file and thus the reduced lines. Is this what you are referring to?
2. ruff tries to merge as much imports into a single line (88 chars) as possible if legibility rule is not broken. It will use single line for multiple imports for cases where single merge imports does not make sense. This is what I have observed.

**Comment by hnyls2002** [comment]
@Qubitium Yeah, I like it removing unused things. But I used `ruff --fix` to format the `interpreter.py` files, it did not merge multiple imports into a single line. 

My ruff version is `0.3.4`, and I do not know why.

**Comment by Qubitium** [comment]
@hnyls2002 We have the same ruff version so not sure our results are so different. I will investigate and check back. Did you run `ruff python --fix` or on a specific file?

**Comment by hnyls2002** [comment]
Oh, I just found out why... I did not run `isort` as `isort` will merge the imports at first...

**Comment by Qubitium** [comment]
@hnyls2002  ruff has isort builtin. I will test, if result same or similar, we can remove isort and directly use ruff. 

https://github.com/astral-sh/ruff/issues/465

EDIT: https://github.com/astral-sh/ruff/pull/633

Based on the isort support, it has limitations. We need to stick with isort for now.

**Comment by hnyls2002** [comment]
@Qubitium 
```
ruff python                                                                                 
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
```
It seems that your usage is not formatting but linting the repos, no wonder why it is likely to compress multiple imports into one line, this is actually done by `isort` and has no relationship with `ruff`.

I tested `ruff format` and it still expands multiple imports into multiple lines, I also think this is the correct way. We need more exploration about this.

**Comment by Qubitium** [comment]
@hnyls2002  Confirmed. isort is dong the import merges and russ is only fixing the safe lints errors. I will work on this more.

**Pull request closed without merging**
