### PR TITLE
Add OpenRouter backend

### PR DESCRIPTION
**Pull request by janimo**
This allows using the models listed here

https://openrouter.ai/docs#models

### CODE REVIEW

**Comment by janimo** [comment]
The dep changes (numba, tqdm, tiktoken) are unrelated to openrouter functionality.

**Comment by merrymercy** [comment]
If OpenRouter uses OpenAI-compatible API, why do we need a new file `openrouter.py`? Can we just delete this file and make one usage example about OpenRouter? see https://github.com/sgl-project/sglang/blob/51104cd405a9573a872e846ba4d85a4298f92c4f/examples/quick_start/together_example_chat.py#L57-L61

**Comment by janimo** [comment]
That would indeed be much cleaner. I know that is what I tried first last week after seeing the together example but it did not work.
I'll need to retry with is_chat_model set.

Openrouter uses this lib for the HTTP message formats but otherwise it has some differences - only chat API (no legacy completions API) so no need for the is_chat_model flag.
For now the kwarg list is the same but their doc exposes more https://openrouter.ai/docs#requests

**Comment by merrymercy** [comment]
let us try to reuse OpenAI backend first. Could you help us fix the errors you see (for together)?
For more options, we can probably use these arguments to set more options
https://github.com/sgl-project/sglang/blob/51104cd405a9573a872e846ba4d85a4298f92c4f/python/sglang/backend/openai.py#L49-L51

**Comment by janimo** [comment]
The together example worked. Just replacing the url and key with openrouter ones did not work. I have tried now with is_chat_model set to true and it is indeed better, but the model-specific chat template is applied (get_chate_template called by higher layers). In openrouter always messages are passed and no templates are used. 
This is how the stream part of the example script shows up with the gemma model:

```
 ========== stream ==========

You are a helpful assistant.<start_of_turn>user
What is the capital of the United States?<end_of_turn>
<start_of_turn>model
Sure, here is the answer: Washington, D.C. (District of Columbia)<end_of_turn>
<start_of_turn>user
List two local attractions.<end_of_turn>
<start_of_turn>model
Sure, here are two local attractions in Washington, D.C.:

1. The Lincoln Memorial
2. The Washington Monument<end_of_turn>

```

whereas without the template it does not have the start of turn and end of turn markers. But maybe it is more correct with them in there, I don't know.

**Comment by janimo** [comment]
I remember now. I was trying the together_example_completion.py example and that did not work.
Together exposes both the OpenAI completions (legacy) and chat APIs. Openrouter only has the chat API.
These are selected by the is_chat_model flag in the backend and it is true for openrouter.
But that flag also selects whether it uses the text_ or messages_ field as prompt. And for the completion example, even if the API is chat only, text_ will be filled for the backend and messages_ is empty.
So I guess there is no need for a completions example for openrouter if it is for testing that API only.

**Comment by merrymercy** [comment]
Yes. You can add a chat example. You do not need to worry about the chat template. We send a message list to OpenRouter and will let OpenRouter handle it.

Please follow up and fix this PR

**Comment by janimo** [comment]
Made a new PR with only the example script.

**Pull request closed without merging**
