### PR TITLE
Instructions on Profiling SGLang Infer System with AMD GPUs

### PR DESCRIPTION
**Pull request by leishaoSC**
## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/contributor_guide.md).
- [x] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by HaiShaw** [comment]
@leishaoSC , LGTM and thanks!

**Comment by zhyncs** [comment]
May we consider adding this document to https://github.com/sgl-project/sgl-project.github.io cc @zhaochenyang20

**Comment by merrymercy** [comment]
@leishaoSC Thanks for the contribution. Can you resolve the conflicts?

**Comment by leishaoSC** [comment]
> @leishaoSC Thanks for the contribution. Can you resolve the conflicts?

@merrymercy I have resolved the conflicts just now. Thanks.

**Comment by merrymercy** [comment]
@leishaoSC Can you fix the lint?

**Comment by merrymercy** [comment]
It still fails. Can you try https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md#format-your-code?

**Comment by leishaoSC** [comment]
> It still fails. Can you try https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md#format-your-code?

I have formatted my code. does it work now? Thanks

**Comment by leishaoSC** [comment]
@merrymercy , I found in "cat .github/pull_request_template.md" my last 3 lines are unchecked. Is this ignorable or not? In addition, could you please help to rerun lint check? Thanks.

**Comment by leishaoSC** [comment]
Hi @merrymercy , I have made server.sh, client.sh, loadTracer.sh executable before I add/commit/push. However, I still saw the error "check that scripts with shebangs are executable..........................Failed
- hook id: check-shebang-scripts-are-executable
- exit code: 1". Could you please suggest how to fix it? Thanks.

**Comment by merrymercy** [comment]
You can delete the  `check-shebang-scripts-are-executable` check in https://github.com/sgl-project/sglang/blob/f9a377f6501b92896263a8210b45bfcaabe89f2a/.pre-commit-config.yaml#L20. I think it is too restrict.

But you also failed multiple other tests such as `trim trailing whitespace`. Can you make sure they pass locally before pushing?

**Comment by leishaoSC** [comment]
> You can delete the `check-shebang-scripts-are-executable` check in
> 
> https://github.com/sgl-project/sglang/blob/f9a377f6501b92896263a8210b45bfcaabe89f2a/.pre-commit-config.yaml#L20
> 
> . I think it is too restrict.
> But you also failed multiple other tests such as `trim trailing whitespace`. Can you make sure they pass locally before pushing?

@merrymercy , I have delete the `check-shebang-scripts-are-executable` check in in my local .pre-commit-config.yaml. But when I ran "pre-commit run --all-files", I still saw one check failed, "don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1". In my local test, other checks all passed. Could you please suggest how I fix the "don't commit to branch" failed issue? In addition, what do you suggest I do to avoid the commit has more failed check on the Lint test? Thanks.
image

**Comment by leishaoSC** [comment]
Hi @merrymercy, I created a new PR https://github.com/sgl-project/sglang/pull/1966 from another feature branch. Hope it can work this time. Thanks.

**Pull request closed without merging**
