### PR TITLE
chore: update ao v0.7.0

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

cc @HandH1998 

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/references/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
https://github.com/sgl-project/sglang/actions/runs/12276585493

**Comment by zhyncs** [comment]
After this update, the QQQ code can be removed from vLLM's dependencies. @HandH1998

**Comment by zhyncs** [comment]
We may consider continuing the migration of turbomind quant to torchao.

**Comment by HandH1998** [comment]
> After this update, the QQQ code can be removed from vLLM's dependencies. @HandH1998

Got it. I will do this these days.

**Pull request merged**
