### PR TITLE
Support MiniCPM3

### PR DESCRIPTION
**Pull request by Achazwl**
## Motivation

Add support for the new model [MiniCPM3-4B](https://huggingface.co/openbmb/MiniCPM3-4B)

## Modifications

I added a new file in `python/sglang/srt/models` called `minicpm3.py`.
The main difference between the old `minicpm.py` and the newly added `minicpm3.py` is LongRope and MLA.
The MLA implementation is basically the same as `DeepSeek-V2`.

## Checklist

- [x] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
@Achazwl Nice work! And happy to see MiniCPM3 also uses MLA.

**Comment by zhyncs** [comment]
@Achazwl Could you please review the conflicts and resolve them?

**Comment by Achazwl** [comment]
For correctness:

`CUDA_VISIBLE_DEVICES=0 python3 scripts/playground/reference_hf.py --model openbmb/MiniCPM3-4B`

```
/mypath/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/mypath/site-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.

========== Prompt 0 ==========
prefill logits (final) tensor([-6.4453,  0.1036,  1.7217,  ..., -6.7773, -6.7773, -6.7773],
       device='cuda:0')
<s> The capital of France is Paris.

- Paris, the capital of France, is a global city
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

========== Prompt 1 ==========
prefill logits (final) tensor([-5.9375,  0.6885,  2.7285,  ..., -6.7656, -6.7656, -6.7656],
       device='cuda:0')
<s> The capital of the United Kindom is London.

- London is the capital and largest city of England, and
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

========== Prompt 2 ==========
prefill logits (final) tensor([-6.4648, -0.6143,  1.9131,  ..., -6.2188, -6.2188, -6.2188],
       device='cuda:0')
<s> Today is a sunny day and I like to spend my time outside. I have a few tasks that I need to complete
```

`python3 -m sglang.bench_latency --model ../models/MiniCPM3-4B/ --correct --output-len 16 --trust-remote-code`

```
Init nccl begin.
Load weight begin. avail mem=76.71 GB
Loading pt checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
/mypath/site-packages/vllm/model_executor/model_loader/weight_utils.py:416: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(bin_file, map_location="cpu")
Loading pt checkpoint shards: 100% Completed | 1/1 [00:03<00:00,  3.61s/it]
Loading pt checkpoint shards: 100% Completed | 1/1 [00:03<00:00,  3.61s/it]

Load weight end. type=MiniCPM3ForCausalLM, dtype=torch.bfloat16, avail mem=68.42 GB
Memory pool end. avail mem=8.83 GB
Capture cuda graph begin. This can take up to several minutes.
max_total_num_tokens=50072

input_ids=[[1, 1507, 8107, 1379, 8360, 1410], [1, 1507, 8107, 1379, 1358, 3532, 24093, 1390, 1410], [1, 13393, 1410, 1348, 39263, 2676, 1384, 1417, 1972]]

prefill logits (first half): tensor([[-6.1562, -0.6602, -0.2852,  ..., -5.8438, -5.8438, -5.8438],
        [-6.1562, -0.6602, -0.2852,  ..., -5.8438, -5.8438, -5.8438],
        [-5.7188, -0.6875,  2.3125,  ..., -5.9688, -5.9688, -5.9688]],
       device='cuda:0') 

prefill logits (final): tensor([[-6.4375,  0.0732,  1.7734,  ..., -6.7812, -6.7812, -6.7812],
        [-5.9375,  0.6953,  2.7656,  ..., -6.7812, -6.7812, -6.7812],
        [-6.4375, -0.6094,  1.8594,  ..., -6.1875, -6.1875, -6.1875]],
       device='cuda:0') 

========== Prompt 0 ==========
<s> The capital of France is Paris.

- Paris, the capital of France, is a global city known 

========== Prompt 1 ==========
<s> The capital of the United Kindom is London.

- London is the capital and largest city of England, and is 

========== Prompt 2 ==========
<s> Today is a sunny day and I like to spend my time outdoors. I have a few activities planned for the day. First 
```

**Review by zhyncs — APPROVED** [review]
@Achazwl Thanks for your contribution! Overall LGTM.

**Comment by zhyncs** [comment]
Hi @Achazwl Are you currently interning at OpenBMB? Thank you again for your contribution. https://x.com/zhyncs42/status/1833444567959408876

**Pull request merged**
