### PR TITLE
Add the ability to enable and disable the Profiler via HTTP API.

### PR DESCRIPTION
**Pull request by Abatom**
## Motivation

1. Add `/start_profile` and `/stop_profile` to enable and disable the profiler for long-term monitoring.

Usage example
1. Set environment variables to specify the save path for trace files, for example:
```
export SGLANG_TORCH_PROFILER_DIR=/home/work/
```
2. Enable and disable profiling.
```
curl http://localhost:30000/start_profile -H "Content-Type: application/json"
curl http://localhost:30000/stop_profile -H "Content-Type: application/json"
```
3. Trace file will be generated in the path from the first step, for example:
```
/home/work/1728625868.5155685.trace.json.gz
```
4. Use the link(https://ui.perfetto.dev/) to load the trace file.

## Checklist

- [ ] Format your code according to the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Add unit tests as outlined in the [Contributor Guide](https://github.com/sgl-project/sglang/blob/main/docs/en/contributor_guide.md).
- [ ] Update documentation as needed, including docstrings or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
Interesting, support Chrome trace is indeed a good idea. May you write a brief doc to describe this feature usage?

**Comment by Abatom** [comment]
> Interesting, support Chrome trace is indeed a good idea. May you write a brief doc to describe this feature usage?

Sure.

1. Set environment variables to specify the save path for trace files, for example:
```
export SGLANG_TORCH_PROFILER_DIR=/home/work/
```
2. Enable and disable profiling.
```
curl http://localhost:30000/start_profile -H "Content-Type: application/json"
curl http://localhost:30000/stop_profile -H "Content-Type: application/json"
```
3. Trace file will be generated in the path from the first step, for example:
```
/home/work/1728625868.5155685.trace.json.gz
```
4. Use the link(https://ui.perfetto.dev/) to load the trace file.

**Comment by zhyncs** [comment]
Yeah I’m familiar with https://ui.perfetto.dev/. Thanks for the guidance.

**Comment by merrymercy** [comment]
@abatom Thanks for the contribution. It is merged.

**Pull request merged**
