### PR TITLE
Add openai embedding API

### PR DESCRIPTION
**Pull request by Ying1123**
This is a follow-up PR for
- #983 
- #987 
- #988 

For embedding API, input as a list will be covered in the next PR.

### CODE REVIEW

**Review by yichuan-w — APPROVED** [review]

**Comment by yichuan-w** [comment]
LGTM

**Comment by yichuan-w** [comment]
btw, I have one small question, why switch the max_num_tokens from 1 to 0?

**Comment by Ying1123** [comment]
> btw, I have one small question, why switch the max_num_tokens from 1 to 0?

Did you mean switch from 0 to 1? This is because our default logic for generation model suppose it will generate 1 token after prefill. Although embedding models do not generate tokens, I added one dummy token to cheat with the shared part of the code.

**Comment by yichuan-w** [comment]
> > btw, I have one small question, why switch the max_num_tokens from 1 to 0?
> 
> Did you mean switch from 0 to 1? This is because our default logic for generation model suppose it will generate 1 token after prefill. Although embedding models do not generate tokens, I added one dummy token to cheat with the shared part of the code.

I see, thanks for answering

**Pull request merged**
